00-short-introduction-to-Python.md
I find the statement "lists are the most common data structure" without any qualifications a bit odd.
In particular, in data science, lists should not be used to store your data set. Operations on lists are waaayyy to slow. Data should be stored using pandas or numpy.
I'm not sure if that was meant. If you are thinking about general python, you could argue tuples are more common. However, that is not really relevant to the material here.
=> Remove "lists are the most common data structure" phrase

05-loops-and-functions.md
PR makes two alterations to the `for` loop lesson:
1. Wording choice nitpick
* "returns" is used as in "carriage return", but "return" is also used in this lesson to refer to the `return` keyword. I'm hoping "new line" might avoid any potential for learners to be tripped up by the challenge.
2. The first introduction example to a `for` loop introduces two concepts at once -- a `for` loop and the idea that `str` is a collection that can be iterated over
* Proposed change substitutes example datatype with a `list`, something that had been already explained as a collection in the `00-short-intro...`
* Not included, but I wonder if we might introduce the `len("a string")` and `"string"[0]` concepts in the introduction lesson
* On a related note, `00-short-intro...` shows examples of `for` …
=> Revise wording and example in "for" loop introduction

01-starting-with-data.md
df.colname notation has not been introduced. Using the notations interchangeably is confusing for someone who is new to pandas. 
See issue #87.
=> use dict notation for column access

06-plotting-with-matplotlib.md
Fix numbered list continuation typo in [lesson 6](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/06-plotting-with-matplotlib.md) by correctly indenting code blocks
=> Fix numbered list continuation typos in lesson 6

06-plotting-with-matplotlib.md
This pull fixes a few minor markdown syntax errors and link in the page for lesson 6.
=> lesson 6: fix markdown syntax

_includes/syllabus.html
Have fixed two typos in the naming of the link and issue #136 raised about the set up link that goes nowhere.
=> Fixing typos

_episodes/00-short-introduction-to-Python.md
Closes #143.
Addresses #81.
- Correct Python errors and inaccuracies.
- Update style to be consistent with Python docs and PEP8
- Add a tip addressing functions for #143
=> Edit Python overview

_episodes/02-index-slice-subset.md, _episodes/04-merging-data.md
Add small clarification for negative index slicing.  Simplify data subset by using 'tail' instead of the confusing all (except last element) slice.  Makes the re-import correct by removing the extraneous index column.
=> simplify commands, clarify slicing, remove index

_episodes/01-starting-with-data.md
Using `survey_df.columns.values` instead of simply  `survey_df.columns` triggers a question "what is the meaning of 'values' and why do we need that". We don't actually need `.values` in this case, so I suggest removing it.
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we …
=> Unneeded example complication

_episodes/02-index-slice-subset.md
The text said
>  With iloc, the start bound and the stop bound are inclusive.
which is not true. Fixed
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process …
=> Fixed a mix-up in `loc` and `iloc` inclusiveness

_episodes/00-short-introduction-to-Python.md, _episodes/01-starting-with-data.md
The main goal in this P.R. was to introduce the `type()` function earlier (in the 1st lesson rather than the 2nd). It's a pretty useful tool for Python learners, and the idea of types is already being discussed in the 1st lesson.
I also wanted to remove the references to `__class__` from the second lesson. I think it's probably too advanced and doesn't add anything beyond `type`.
The rest is mostly incidental wording changes I made while I was in the neighborhood, which I hope are improvements.
=> Introduce type function earlier + some wording changes

setup.md
Related to issue #221 but doesn't resolve it.  
Added option to download add data files from a single zip file.  Also updated all data file urls to point to the data directory for the repository, to 1) be consistent (for any future updates), and 2) make downloads automatic (previous links were to github pages, not raw files).
=> Updated data file download links in setup

_extras/guide.md
For mac os,  I think using homebrew is much more convenient than using anaconda to install workshop dependencies. I haven only tried on the high Sierra though
=> Setup alternative for mac os

_episodes/05-loops-and-functions.md
There is no need to show the function `yearly_data_arg_test` once again; there are basically no changes compared to the function defined above. Moreover, in the body the condition is checked via `if not`, and not with `if is None` as above. Though both functions yield the same result in the present use case, it is probably more confusing than helpful to provide two different ways for checking the condition.
=> remove redundant code segment and white spaces

_episodes/06-visualization-ggplot-python.md
After the merge of PR #248, I noticed that a section of the faceting section was not rendering well:
Actually, this was due to a set of old text/paragraphs still in the new text, whereas the actual challenge was already reformulated just below that section. This PR removes the redundant text from the old text (and fixes an additional small typo).
=> Plotnine fix

CONTRIBUTING.md
include reference to _episodes folder when describing location to lesson files
Wasn't entirely obvious where to find the files for each topic, so I added a reference to the _episodes folder.
=> CONTRIBUTING.md: add a pointer to the _episodes directory

_episodes/01-starting-with-data.md
Challenge Q is confusing due to mix jargon: "site ID" and site names when referring to "plot_id" column. I think having it csv column labelled as "site_id" (originally) in the data is more meaningful/understandable to new users than "plot_id"
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the …
=> Update: 01-starting-with-data.md

_extras/CONTRIBUTORS.md
Moving `CONTRIBUTORS.md` to `_extras` folder so that the page is linked from within the `Extras` menu.
=> Move CONTRIBUTORS.md to _extras

CONDUCT.md, reference.md, setup.md
Right now these pages do not render correctly:
http://www.datacarpentry.org/python-ecology-lesson/reference/
http://www.datacarpentry.org/python-ecology-lesson/setup/
http://www.datacarpentry.org/python-ecology-lesson/conduct/
Removing "permalink" from the header seems to work. I also don't see permalink being specified in the lesson-example:
https://github.com/carpentries/lesson-example
=> Fix rendering of some pages

_episodes/02-starting-with-data.md
I fixed two small typos: 
1. my -> may
2. Added a space between two sentences.
=> Fixed small typos

setup.md
Fix issue #306. Pretty simple, but it would be great to have a second set of eyes on.
=> move to figshare links

_extras/guide.md
Deleted specific mention to 'Mac OS with Homebrew' as installation in [Setup](https://datacarpentry.org/python-ecology-lesson/setup.html) is now based on conda/Anaconda for all platforms.
=> deleted outdated reference

_episodes/05-merging-data.md
Please delete the text below before submitting your contribution.
=> 05-merging-data.md: use proper file name

_episodes/01-short-introduction-to-Python.md
Refers to #335 - `dict` values should never be referred to by position, but by key.
=> 01-short-introduction-to-Python.md: reference value in dict by key and not position

_episodes/03-index-slice-subset.md
Replaced generic dataframe name `df` by lesson-specific `surveys_df`
=> 03-index-slice-subset.md: use proper dataframe name

_episodes/03-index-slice-subset.md
The  sentence refers to x > 5, I think there is an extra "not"
Wil
=> 03-index-slice-subset.md: improve wording

_extras/guide.md
Updated question and answer in section **Dictionaries Challenges** based on corresponding section in episode [01-short-introduction-to-Python.md](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/01-short-introduction-to-Python.md)
=> guide.md: update Q&A in "Dictionaries Challenges" section

_episodes/08-putting-it-all-together.md
This pull request addresses some distracting formatting issues in [Episode 8](https://datacarpentry.org/python-ecology-lesson/08-putting-it-all-together/index.html):
* Near the bottom of the page, under the header *Challenge - Pandas and matplotlib*, the challenge and answer are not rendered properly. This was due to a line break in the middle of the answer.
* Just below that, under the header *Saving matplotlib figures*, the tip is not formatted correctly and the text is rendered as code.
=> clean up formatting in episode 08-putting-it-all-together

_episodes/01-short-introduction-to-Python.md
Added the highlights of episode 1 at the end of the page.
=> 01-short-introduction-to-Python.md: add keypoints

_episodes/01-short-introduction-to-Python.md
A missing quote at the end of the YAML in section 01 meant it wasn't being read and didn't show up on the table in the home page
=> 01-short-introduction-to-Python.md: Add missing quotation mark

setup.md
I don't understand why this was done in #231. GitHub has built-in download links, I was surprised to see this fancy JavaScript service being used for this.
This seems like a 404 waiting to happen, and can't be good for accessibility.
[This is what DownGit itself uses anyway](https://github.com/MinhasKamal/DownGit/blob/def14cef2a5d9fe4bef3227c38de425e5c145c60/app/home/down-git.js#L152-L153):
```javascript
var downloadUrl = "https://github.com/"+repoInfo.author+"/"+
repoInfo.repository+"/archive/"+repoInfo.branch+".zip";
```
=> Use GitHub link instead of "DownGit" service

_extras/guide.md
In the instructor notes, there is an extra ` in one of the commands
=> Removing unnecessary `

_episodes/07-visualization-ggplot-python.md
Fix the bad hash in the following link:
change https://plotnine.readthedocs.io/en/stable/api.html#Color-and-fill-scales
to
https://plotnine.readthedocs.io/en/stable/api.html#color-and-fill-scales
=> 07-visualization-ggplot-python.md: fix link

_episodes/01-short-introduction-to-Python.md
I suggest removing the statement about the order in Python dictionaries. The behavior has changed between Python 3.5, 3.6, and 3.7 and it would be a bit too difficult to explain.
=> 01-short-introduction-to-Python.md: remove statement about order in Python dicts

_episodes/01-short-introduction-to-Python.md
Hello :-) I wondered whether it was intentional that only 2 of the 3 initially introduced variables are reused in the immediately following examples. If not, here's a suggestion to do just that.
=> Re-use previously introduced variables

_episodes/01-short-introduction-to-Python.md
There is a typo/error within the file. The value of the `number`
variable is set to `42` on line 84. However, the line `151` shows `11`
instead of `42`. This might be confusing to people/instructors.
=> Fix typo that shows a wrong value of the `number` variable.

_episodes/01-short-introduction-to-Python.md
The `po` files are the tokenised version of the lessons. The [tool we are using](https://github.com/carpentries-i18n/po4gitbook) complains if the following *typos* or empty lines at the end of sections are not fixed.
=> [translations] Clean lessons to create po files

_episodes/01-short-introduction-to-Python.md
Remove unordered from dictionary definition in keypoint summary to limit confusion
=> Unordered dictionaries

_episodes/03-index-slice-subset.md
Simple fix for a minor typo in the third episode. The line I changed was automatically reading "0." as the start of a list and parsing it incorrectly on the page itself. I've put '0' in code backticks, which should fix the display.
=> Fixed typo in the list lesson.

_extras/guide.md
Have to undo one recent change introduced in #435 in order to keep the section consistent with what it was doing before. Also, while at it, add spaces around `+`.
@katrinleinweber, LGTY?
=> guide.md: remove space after comma in 'Basic Loop Challenges'

_episodes/07-visualization-ggplot-python.md
This addresses issue #426 
Adds a reminder callout which links to the setup page, in case the learner has not yet installed plotnine.
=> add reminder about plotline installation

_extras/guide.md
Add content to Instructors Guide to Python Ecology lesson, particularly the final (SQL) section.
(part of instructor check-out).
=> Hot007 issue307 update guide

setup.md
@maxim-belkin, I have made an attempt at improving the instructions for setup I had raised as #457. Some of it is directly copied from the Software carpentry setup instructions including the setup videos. Other bits I added myself. 
Let me know if you want me to change anything further. 
It may also be nice to change the html template for Python for DC lessons to look a bit more like the SC ones such as this one:
https://edcarp.github.io/2020-01-21-edinburgh-swc/
But I think this will require the change of the actual workshop-template.
=> Adding extended setup instructions

_episodes/02-starting-with-data.md, _episodes/06-loops-and-functions.md, _episodes/08-putting-it-all-together.md
<details>
As requested by maxim-belkin in [issue 364](https://github.com/datacarpentry/python-ecology-lesson/issues/364), I changed mentions of "IPython Notebook" to "Jupyter Notebook" to maintain consistency throughout the whole lesson.
</details>
=> Change IPython Notebook to Jupyter Notebook

_episodes/03-index-slice-subset.md
Setting sex to x is not used in the next step of the challenge.
---
When I took the course, challenge 1 in the "Challenge - Putting it all together" section of the lesson 03-index-slice-subset was a bit confusing. 
> 1. Create a new DataFrame that only contains observations with sex values that
>   are **not** female or male. Assign each sex value in the new DataFrame to a
>   new value of 'x'. Determine the number of null values in the subset.
The [Lesson guide](https://datacarpentry.org/python-ecology-lesson/guide/) shows this solution:
```python
new = surveys_df[~surveys_df['sex'].isin(['M', 'F'])].copy()
new['sex']='x'
print(len(new))
```
This returns: `2511`, which is the same as:
```python
sum(surveys_df['sex'].isnull())
```
However, as written in the lesson guide, setting 'sex' to …
=> Clarifying challenge and removing unnecessary step

_extras/guide.md
=> link to _includes/scripts/

_episodes/00-before-we-start.md
Changes folder in the introductory suggested project layout from **scripts** to **code**
Referenced in issue #471, the *Before we start* episode 0 suggests keeping Python code in a **scripts** folder.
Unfortunately, Anaconda has a built-in `scripts` module that will shadow the student's **scripts** folder and make
```
import scripts.example
```
fail.
The issue suggests adding an `__init__.py` to **scripts**.
That adds unnecessary complexity to the introductory material and this PR proposes renaming the folder.
=> PR to address issue #471

_episodes/03-index-slice-subset.md
Comment & code refers to *rows* while text mistakenly refers to *columns*
Fix to #479
=> Fix typo in Indexing, Slicing & Subsetting episode

_episodes/05-merging-data.md
Clarified some text to point out that empty values in a CSV are by default converted to NaN. The option `keep_default_na=False, na_values=[""]` is not necessary to replace empty with NaN. Good to point the learner to the options of read_csv, though.
<details>
materials, we …
=> Updated the text for read_csv import option

episodes/03-index-slice-subset.md
Clarification according to #514. Emphasize that iloc is for index with number, and loc is for labels.
=> Issue 514: clarify iloc and loc

episodes/01-short-introduction-to-Python.md, instructors/instructor-notes.md
Inspired in part by the [Instructor Notes Drive](https://carpentries.org/blog/2023/05/instructor-notes-drive-schedule/), I am going to work through the lesson episode-by-episode, relocating the exercise solutions to their relevant challenge blocks. To make the changes easier to review, I am going to create one PR per episode.
This PR takes care of the solutions for challenges in episode 2, _Short introduction to programming in Python_
This is related to #542
=> relocate solutions for episode 01

episodes/04-data-types-and-format.md, episodes/07-visualization-ggplot-python.md, instructors/instructor-notes.md
This Instructor Note will be more helpful presented inline, next to the section that it relates to. This PR moves it there.
[Edit]: I found a similar note for episode 07, so I have updated this PR to also add an inline note there.
=> move instructor notes about data checkpoint inline

episodes/02-starting-with-data.md
PR for issue https://github.com/datacarpentry/python-ecology-lesson/issues/564 
Pandas version >= 2 changes the default argument of .mean to numeric_only = False from numeric_only=True
This PR just inserts numeric_only=True into the relevant three lines
=> Fix default values of .mean for pandas version >= 2

.editorconfig
If on the same line of the value they describe, then they cause an error in some editors (e.g. nvim)
=> move .editorconfig comments one line above

episodes/04-data-types-and-format.md
Fixes #549 by updating the reference to the error in the instructional text. To avoid confusion, the deprecated behavior (raising a `ValueError`) is also mentioned.
This is a contribution as part of my instructor checkout.
=> fixes a reference to an outdated error type

episodes/01-short-introduction-to-Python.md
Adds a link to docs.python.org/3/, to help learners find the documentation that we recommend in the episode
=> link to Python documentation

learners/setup.md
Fixes #574 by updating the path to the environment file.
_This is a contribution as part of my instructor checkout._
=> Fix environment link in setup page

episodes/03-index-slice-subset.md
In the interest of better readability, this PR adds consistency to the comparison operators list by:
* Putting `<` and `>` on their own lines just as `<=` and `>=` are on their own lines
* Adding colon at each definition (only some terms had this colon)
=> Add consistency to comparison operators list

learners/jupyter_notebooks.md
To  create a new Python notebook, we say to use the "New" menu but don't say what to select in that menu. This PR fixes that.
=> how to create new python notebook

learners/setup.md
closes #601 
Add fenced div to highlight need to keep terminal window used to launch Jupyter open.
=> Add note about leaving terminal open when using Jupyter
