datacarpentry/python-ecology-lesson

- 00-short-introduction-to-Python.md
- 01-starting-with-data.md
- 08-working-with-sql.md
Typos and other minor fixes (mostly cherry-picked commits from @fmichonneau that I am belatedly merging)
> Various fixes

- 01-starting-with-data.md
Proofreading lesson 1 with a focus on clarity and consistency.
> Proofreading lesson 1

- 01-starting-with-data.md
- 02-index-slice-subset.md
- 03-data-types-and-format.md
- 04-merging-data.md
- 05-loops-and-functions.md
- 06-plotting-with-matplotlib.md
I have adjusted lessons to use FigShare instead local files.
Some of used files are not on FigShare and therefore I left the way they are used in the code unchanged.
Fixes #23
> Use FigShare

- 00-short-introduction-to-Python.md
- 03-data-types-and-format.md
- 05-loops-and-functions.md
- 07-putting-it-all-together.md
- 08-working-with-sql.md
> Migrate lessons to python 3

- 01-starting-with-data.md
- 02-index-slice-subset.md
- 03-data-types-and-format.md
- 04-merging-data.md
In previous pull request I missed few things that does not work with figshare dataset. Mostly using `species` instead of `species_id`. So now I fixed those. Hope it's all of them.
> Use figshare fix

- 01-starting-with-data.md
- index.md
Most links had been fixed, but index.md and the intro to 01-getting-started-with-data.md still needed to be fixed.
> fixed data file links to point to data on FigShare

- 08-working-with-sql.md
The link was broken, so I fixed it.
> Fix broken link

- 06-plotting-with-matplotlib.md
This patch contains two simple fixes because.
> modified code description and column name

- 03-data-types-and-format.md
The use of NaN to denote missing data is a feature of Pandas
> Changed Python to Pandas

- 03-data-types-and-format.md
To clarify that "int" function doesn't round to the nearest integer
> A more effective example of rounding down

- _config.yml
- css/lesson.css
John,
It occurred to me that I could make a clean pull request from here.  I hope I haven't managed to bollocks this one up, too.
-- justbennet
> Switch to kramdown and suppress pink background from <pre>

- 01-starting-with-data.md
This is the cleaned up version of my instructor training pull request.  John slipped in a change to the
Python doc, which I incorporated, hence it appears there are two commits to this pull request instead of one.  This should result in all and only the changes I intended to make.  Sorry for the bumbling.
This addresses a concern expressed by @mboisson in Issue 24.
> Modified 01starting-with-data.md to use .csv files instead of URLs

- 00-short-introduction-to-Python.md
This adds another space before inline comments and changes the modulo example to use number that make it easier to deduce what "modulo" means from context.
> Improve binary operator introduction examples

- 05-loops-and-functions.md
Created challenge to adjust the step in range function when creating csvs as part of _Automating data processing using For Loops_.
Added as part of Software and Data Carpentry instructor training checkout.
> New challenge using range step in loops exercise

- 00-short-introduction-to-Python.md
This small change is meant to improve the reading material. It is also meant for becoming a DC Instructor.
> Some small typo and rewording of a statement

- 03-data-types-and-format.md
PR groups learning objectives into two (rather than five) levels, as per
comments on initial PR (https://github.com/datacarpentry/python-ecology-lesson/pull/63) to update learning objectives. This two-level format is encouraged going forward to reduce visual clutter for learners.
> group learning objectives into two main levels

- 01-starting-with-data.md
The original text is "Let's next create a list of unique species in our data", which would need a statement like
` df.species_id.nunique()`, when in fact what we are doing is `surveys_df.groupby('species_id')['record_id'].count()`, which is the number of samples in each species.
> Make instructions a little clearer

- 00-short-introduction-to-Python.md
update to clarify ordered and unordered nature of (lists and tuples) and dictionaries, respectively.
Adds mentions to this aspect of these datatypes, and attempts to offer a simple explanation of how this can affect code in dictionary settings.
Submitted for Data Carpentry instructor training for Asher Haug-Baltzell (ahaug@email.arizona.edu).
> 00(python intro): ordered-unordered clarification

- 05-loops-and-functions.md
The student has already used `pd.unique()` to see all unique species, so they could copy and paste that into a list here to iterate over. But hopefully they will realize that they can make a list directly from `pd.unique()` to use in the for loop. A good concept of letting the code discover what needs to be done. 
Ideal answer:
```all_species_ids=surveys_df['species_id'].unique()
for species_id in all_species_ids:
survey_spp=surveys_df[surveys_df.species_id == species_id]
filename = 'data/surveys' + str(species_id) + '.csv'
survey_spp.to_csv(filename)
```
> Make a loop over values that must be pulled from the data. - Instructor training assignment

- _includes/pythonSetup.html
- index.md
Addresses https://github.com/datacarpentry/python-ecology-lesson/issues/36
> added installation instructions to index.md

- 01-starting-with-data.md
The DataFrame index was not explained in the lesson. I have added some information about that.
> added information about indexes in a dataframe

- 00-short-introduction-to-Python.md
- 01-starting-with-data.md
- 02-index-slice-subset.md
- 04-merging-data.md
As suggested in issue #71, variables in segments 0-4 have been
renamed from CamelCase to snake_case to standardize the coding style.
> renamed variables from CamelCase to snake_case

- 00-short-introduction-to-Python.md
This is for DC Instructor Training checkout. @gvwilson
> added challenge question on dictionaries to 00

- 05-loops-and-functions.md
I addressed Issue #44 . As suggested this simplifies the instruction and also guards against the possibility of missing years. However, if the point was to introduce the range function then perhaps this change should not be incorporated.
> Addresses issue #44

- 00-short-introduction-to-Python.md
I am submitting this PR in partial fulfillment of my checkout procedure after attending the Instructor Training at SciPy in July. I proof read the document, fixed a few minor typos / grammatical issues, and clarified a bit of technical language.
> Proof read 00-short-introduction-to-Python.md

- SETUP.md
https://github.com/datacarpentry/python-ecology-lesson/issues/85
> first version of SETUP.md

- _includes/pythonSetup.html
- _includes/scripts/check_env.py
Dealing with #83 : I have 
- added a check_env.py in dir _includes/scripts
- edited pythonSetup.html to give instructions on running it.
> check_env script + instructions in pythonSetup.html

- 01-starting-with-data.md
Hello! 
I'm starting a pull request to trim down lesson 01 mentioned in #81. I'm starting this pull request now so that others can offer input into the process. 
My first goal is to consolidate material. Then, based on others input, we can think about how much plotting we should do. 
Any advice or suggestions are greatly appreciated.
> 01 lesson trim

- 08-working-with-sql.md
I added a little more about querying to the sqlite3 lesson.
> added to SQL lesson

- 01-starting-with-data.md
Since "sorted" conflicts with the built-in python function sorted(), renamed the example variable name as "sorted_data"
> fixing naming conflict

- 00-short-introduction-to-Python.md
@qjcg @wrightaprilm @mkuzak 
We are in the process of developing our surveys so that we can have a better understanding of our learners' skills and self-efficacy after taking a Data Carpentry workshop. To do this we want to improve the learning objectives for all of our lessons so that they are measurable. I revised the learning objectives with Erin's help for the Python lesson, and Kate advised that the best way to implement these types of changes would be to submit them as a pull request. I would love to have your feedback and input as maintainers of this lesson, especially with respect to whether we captured the terminology in the LOs correctly. Are you able to take a look at the learningobjectives/PRs and provide feedback by December 28th?​
> Revised learning objectives

- 00-short-introduction-to-Python.md
Added line highlighting that Python indexes from 0.
> 0 Index explanation

- 08-working-with-sql.md
@wrightaprilm 
Added a space between the * on the last learning objective so that it appears as a bulleted item.
> Fixed bullet on learning objective

- _includes/javascript.html
- _layouts/bootcamp.html
- _layouts/lesson.html
Resolves all but the missing image in #92.
> remove jquery references

- _includes/pythonSetup.html
Fixes #127 
Rendered from my fork can be previewed here:
https://mkuzak.github.io/python-ecology-lesson/
> Add ggplot installation instructions.

- 04-merging-data.md
- 05-loops-and-functions.md
- CONTRIBUTING.md
Few variable names missed in pull request #74 
Added point to CONTRIBUTING.md about adhering to PEP8
> Few fixes improving style consistency.

- 00-short-introduction-to-Python.md
> Replace 'batteries-included' with 'general-purpose'

- INSTRUCTORS.md
I corrected typos, spelling mistakes, and some text formatting inconsistencies (mostly adding ticks around code snippets in the text.
> Fixed typos, and text formatting inconsistencies.

- _episodes/00-short-introduction-to-Python.md
- _episodes/03-data-types-and-format.md
I am submitting this pull request as part of my instructor training checkout procedure.
> Revised section 00-intro and 03-data types

- _episodes/01-starting-with-data.md
Rewording for https://github.com/datacarpentry/python-ecology-lesson/issues/154
> Rewording dataframe methods attributes

- _extras/about.md
- _extras/discuss.md
- _extras/figures.md
- _extras/guide.md
- reference.md
For issue https://github.com/datacarpentry/python-ecology-lesson/issues/152
Moved INSTRUCTORS.md to _extras/guide.md
Also put in figures.md, discuss.md and about.md
Updated guide.md to link to figures correctly.
Code blocks still don't seem to be rendering correctly, so I'll create an issue about that.
> moved files to _extras

- _includes/pythonSetup.html
> Add link to raw check_env file

- _episodes/02-index-slice-subset.md
Closes #160 and #161 
This is still a WIP. Copy and references are one of the most confusing concepts for those new to them. I believe it is better to be direct and precise in explaining these two concepts than to have the students experiment to figure out the difference.
Feedback welcome on this draft.
> Lesson 2 - Revise the copy and reference section

- _episodes/01-starting-with-data.md
Closes #87 
This closes the issue re: `groupby` being used before mentioning. I've gone ahead and bolded the first mention of all the methods to make it easier for folks to scan back through the lesson.
> Highlight in bold the first mention of each method

- _episodes/01-starting-with-data.md
- _episodes/02-index-slice-subset.md
- _episodes/03-data-types-and-format.md
- _episodes/04-merging-data.md
- _episodes/05-loops-and-functions.md
- _episodes/06-visualization-ggplot-python.md
- _episodes/07-putting-it-all-together.md
- _episodes/08-working-with-sql.md
> Added motivating questions

- _episodes/01-starting-with-data.md
- _episodes/02-index-slice-subset.md
- _episodes/03-data-types-and-format.md
- _episodes/04-merging-data.md
- _episodes/05-loops-and-functions.md
- _episodes/06-visualization-ggplot-python.md
- _episodes/07-putting-it-all-together.md
- _episodes/08-working-with-sql.md
Added initial timing estimates and the number of challenges for the episodes
A first pass at https://github.com/datacarpentry/python-ecology-lesson/issues/138
> added time estimates

- CITATION
- CONDUCT.md
- CONTRIBUTING.md
- NEWS.md
> added NEWS and updated admin files

- assets/js/lesson.js
- index.md
- setup.md
Updated index.md and setup.md to use the template and match the formatting of other lessons. Some introductory language was also added, so @wrightaprilm @mkuzak @qjcg it would be great to get a review.
Rendered lessons are here: http://tracykteal.github.io/python-ecology/
> updated index and setup

- _episodes/00-short-introduction-to-Python.md
Added consistent explanation of operators + and *
> Fixed #193

- _episodes/08-working-with-sql.md
It seemed to me like the SQLite section was missing a key interaction with the database. It had no information about modifying or creating tables in SQLite. Hopefully this short example should give attendees enough of guide to show them its possible and an example of one way to do it.
> Add section on creating tables to SQLite episode.

- _episodes/01-starting-with-data.md
- _extras/guide.md
For the 01-starting-with-data.md episodes, following adaptations are suggested:
- renamed the variable name used to define the dataframe.groupby object from `sorted_data` to `grouped_data`
- As defined in #190, the current solution in the instructor nodes are confusing. Actually, in the challenge description the usage of `nunique` on the variable `plot_names` does not make much sense. So instead, this is applied to the data frame column instead of the `plot_names` variable
- The syntax of the `total_count` is rather confusing, as the `surveys_df['plot_id']` is used inside the `groupby` operation: `total_count = surveys_df['record_id'].groupby(surveys_df['plot_id']).nunique()`. This is adapted to `total_count = surveys_df.groupby('plot_id')['record_id'].nunique()` which is in line with the …
> Adapt instructor notes and 01 episode

- _episodes/03-data-types-and-format.md
> Renamed character dtype to text dtype.

- reference.md
Submission for Data Carpentry Instructor checkout
The following changes have been made:
- created a glossary with entries and corresponding definitions
> added glossary entries

- _episodes/07-putting-it-all-together.md
- _extras/guide.md
Scientists often operate on mathematical equations. Being able to use them in their graphics has a lot of added value. The provided example is an only slight modification to the original one. Nevertheless, it produces a significantly better result.
> Mentioned the ability to use LaTeX notation in legends and axis labels

- _episodes/00-short-introduction-to-Python.md
Please delete the text below before submitting your contribution. 
The example.py script in the first lesson, 00-short-introduction-to-Python.md, which demonstrates the print function might be confusing as it would not work if run as is. The script was altered so that assignment of the string "Data Carpentry" to the variable "text" was made in the script.
> Add variable assignment to example.py

- _episodes/00-short-introduction-to-Python.md
Proposed fix for issue 217 https://github.com/datacarpentry/python-ecology-lesson/issues/217
> Fixed typo and added clarification on types

- _episodes/05-loops-and-functions.md
This is in regards to issue #225.
> replace 'if loops' statements

- _episodes/01-starting-with-data.md
- _episodes/02-index-slice-subset.md
- _episodes/03-data-types-and-format.md
- _episodes/04-merging-data.md
- _episodes/05-loops-and-functions.md
- _episodes/06-visualization-ggplot-python.md
- _episodes/07-putting-it-all-together.md
This pull request references part of issue #221. I have gone through and corrected and checked the paths to the data files in the lessons. I did not check to make sure that the downloaded data files were placed into a folder named "data". I think this is the case, however.  I also cleaned up a formatting issue where a comment in a python code section was reading as a heading. There were a few weird formatting things I tried to clean up in along the way. Feel free to keep them if they're helpful or leave them if they're not.
> I searched for and corrected paths to data files in lessons. 

- _episodes/00-short-introduction-to-Python.md
- _episodes/04-merging-data.md
- _episodes/05-loops-and-functions.md
- _episodes/06-visualization-ggplot-python.md
- _episodes/07-putting-it-all-together.md
- _episodes/08-working-with-sql.md
- index.md
- setup.md
Addresses most of the suggestions in #232
> Typos and formatting

- _episodes/01-starting-with-data.md
It would be good to help newbies get past the acronym, and to know the benefits and variations of delimited text files. I've added four more sentences to explain. It's not at the first reference to CSV, but to do it earlier might have been distracting.
> Adding an explanation of CSV

- _episodes/00-short-introduction-to-Python.md
- _episodes/01-starting-with-data.md
- _episodes/02-index-slice-subset.md
- _episodes/03-data-types-and-format.md
- _episodes/04-merging-data.md
- _episodes/05-loops-and-functions.md
- _episodes/07-putting-it-all-together.md
- _episodes/08-working-with-sql.md
1. Made comments consistent throughout all episodes (PEP8).
2. Made minor edits (grammar/clarity) to some comments.
3. Changed 'csv' to 'CSV' in descriptive text where this wasn't consistent.
> Consistent comments

- _episodes/01-starting-with-data.md
Including information about formatting at the beginning of exercise 1 in case other users don't see all 9 columns of data. The first time I tried this exercise, that threw me off for a minute.
> Formatting for the columns of data

- _episodes/03-data-types-and-format.md
Addresses issue #241 .
Submitted as part of requirements for instructor checkout.
> Fixed various typos in Lesson 03.

- _episodes/04-merging-data.md
- _episodes/06-visualization-ggplot-python.md
Hi,
@ErinBecker As per the instructions I have update. Let me know if this is ok. #232.
> typos and formatting #232

- _episodes/03-data-types-and-format.md
Fixed inconsistency with respect to variable names df, df1 and df_survey in the section Writing Out Data to CSV
> fixed variable naming

- _episodes/01-starting-with-data.md
- _episodes/02-index-slice-subset.md
- _episodes/03-data-types-and-format.md
- _episodes/04-merging-data.md
- _episodes/06-visualization-ggplot-python.md
- _episodes/08-working-with-sql.md
datacarpentry/python-ecology-lesson#265 changed site_id to plot_id
which make figures used in the lesson inconsistent with the material.
Here we are simply changing `site_id` to `plot_id`
> Changing site_id back to plot_id

- _episodes/00-Before-we-start.md
Rework the intro part of 00-before-we-start.md.
> 00-before-we-start.md: rework the beginning

- _episodes/00-short-introduction-to-Python.md
"Basics of Python" text duplicated from "Before we start"
> removed duplicated text

- _episodes/01-short-introduction-to-Python.md
- _episodes/02-starting-with-data.md
- _episodes/03-index-slice-subset.md
- _episodes/04-data-types-and-format.md
- _episodes/05-merging-data.md
- _episodes/06-loops-and-functions.md
- _episodes/07-visualization-ggplot-python.md
- _episodes/08-putting-it-all-together.md
Update code blocks per issue #266.  Will not change the formatting until the template is updated.
> Code formatting

- _episodes/00-before-we-start.md
> Changed format for Jupyter/Spyder headers. Instructor-training assignment

- _extras/guide.md
changes:
* site_id -> plot_id
* fixed default number of lines for head() and tail()
* misc. stuff
Please delete the text below before submitting your contribution.
> _extras/guide.md: update to match episodes' contents

- _episodes/09-working-with-sql.md
> fix sql command

- _episodes/08-putting-it-all-together.md
I'm not sure why the spacings are different. Does that look OK to you, @maxim-belkin?
> Episode 8: add time estimates

- _episodes/08-putting-it-all-together.md
Tagging @stijnvanhoey as this touches his contribution
> Ep.08: few minor fixes

- index.md
Maxim Belkin is listed as a maintainer on the DC lessons page
> added a maintainer

- _extras/guide.md
Minor change to update number of lesson 01 and name of lesson 07
> guide.md: updated episode number and names

- _extras/guide.md
Updated questions in section **short-introduction-to-Python** to match those in episode [01-short-introduction-to-Python.md](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/01-short-introduction-to-Python.md)
> updated questions in challenge

- _extras/guide.md
Added missing title to Challenge, as derived from corresponding section in 06-loops-and-functions.md
> guide.md: adding missing title

- _extras/guide.md
Please delete the text below before submitting your contribution.
> guide.md: fix typo

- _extras/guide.md
Finished lines with double spaces in Selection Challenges, so they display in different lines
> minor: double spaces to separate

- _extras/guide.md
Moving bug note to a callout box.
> guide.md: bug note as a callout box

- _extras/guide.md
Added Challenge guidelines (taken from the lesson) and language markup to section 04-data-types-and-format for consistency with the other sections.
> guide.md: added consistency to 04-data-types-and-format section

- _extras/extra_challenges.md
Following @maxim-belkin suggestion in #334, this file would store all extra challenges (exercises) that may be useful for instructors in the future.
> extra_challenges.md: new file

- _extras/guide.md
Removed mention and response to challenge that was removed from lesson 06-loops-and-functions.md
> guide.md: removing deprecated challenge

- _episodes/03-index-slice-subset.md
> 03-index-slice-subset.md: cleaning up

- _episodes/03-index-slice-subset.md
"the both start bound and the stop bound" ---> "both the start bound and the stop bound"
> Minor issue with word ordering

- setup.md
1. link to download anaconda
2. link to download mini-conda
> fixed 2 broken links

- _episodes/04-data-types-and-format.md
Fixes #378 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  
---
> 04-data-types-and-format.md: Correct description of default dropna behavior [#379]

- _episodes/04-data-types-and-format.md
"Small steps lead to big change."
:)
> 04-data-types-and-format.md: remove unnecessary space

- _episodes/00-before-we-start.md
Typo: Enviroment -> Environment
The other changes are just removing whitespace and the end of the lines.
> 00-before-we-start.md: fix typo and whitespace

- _episodes/05-merging-data.md
> 05-merging-data.md: fix typo

- _episodes/07-visualization-ggplot-python.md
> 07-visualization-ggplot-python.md: typo

- _episodes/09-working-with-sql.md
typos:
notecable -> noteceable
excercise -> exercise
Also wrapped a long line
> 09-working-with-sql.md: typos, wrapping

- _extras/CONTRIBUTORS.md
> _extras/CONTRIBUTORS.md: typos and links

- _episodes/00-before-we-start.md
1. Fix link reported in #389 
2. Wrap text to 100 characters
3. Change formatting: `### text` to `**text:**` as these `###` are actually part of the same logical unit.
> 00-before-we-start.md: various fixes

- _episodes/07-visualization-ggplot-python.md
1. Fix one broken link pointed by @fmichonneau in #389.
2. Other minor fixes.
> 07-visualization-ggplot-python.md: various fixes

- index.md
Fix link to the lesson setup page
> index.md: fix link to lesson setup

- _episodes/05-merging-data.md
> 05-merging-data.md: fix some code blocks

- _episodes/04-data-types-and-format.md
Fixing a couple of misplaced output boxes.
> fix problem with output rendering

- _episodes/02-starting-with-data.md
Add keypoints for lesson release
> adding keypoints to 02

- _episodes/05-merging-data.md
adding keypoints to 05 for lesson release
> add keypoints to 05

- setup.md
> Link to new conda homepage

- README.md
- index.md
README.md: 
- April resigned last year.
- last commit by Tania dates back to Feb 15, 2018.
index.md:
- remove the list of maintainers.
> Maintainers 2020

- _episodes/01-short-introduction-to-Python.md
- _episodes/04-data-types-and-format.md
- _episodes/06-loops-and-functions.md
This fixes a few places where concepts are referred to as simple or easy, when using these terms seems to be not in line with Carpentries teaching principles.  It does not catch every place where these words are used as there are times where these words have a conversational, rather than dismissive tone.
> Things are not easy or simple

- _episodes/01-short-introduction-to-Python.md
> 01-short-introduction-to-Python.md: Change dictionary keys from integer to strings

- _episodes/03-index-slice-subset.md
Some additional information is provided about avoiding naming conflicts with
built-in data types and methods.
Submitting this pull request as part of the checkout process, but am interested in making further changes as needed to improve this contribution.
> 03-index-slice-subset.md: a comment on reserved words

- _episodes/00-before-we-start.md
- _episodes/01-short-introduction-to-Python.md
- _episodes/02-starting-with-data.md
- _episodes/04-data-types-and-format.md
- _episodes/05-merging-data.md
- _episodes/06-loops-and-functions.md
- _episodes/08-putting-it-all-together.md
- _extras/06-visualization-ggplot-python.ipynb
- _extras/guide.md
- _includes/links.md
- reference.md
- setup.md
As I'm preparing [a workshop](https://tibhannover.github.io/2020-02-13-LSE-Hannover/) with this lesson, I'll collect some typo fixes, formatting improvements, and IMHO better wordings here. Please feel free to review or cherry-pick already.
> Assorted minor fixes and improvements

- README.md
Add a link pointing to the page that lists all issues marked with 'good first issue' label.
> README.md: link to 'good first issue's

- _episodes/03-index-slice-subset.md
- index.md
For Issue #454
The wrong operator shown "=" has been corrected to "==".
> Corrected operator and estimated timing

- _episodes/01-short-introduction-to-Python.md
To be consistent with the paragraphs introducing lists and dictionaries
> Add bold to where tuples and functions are first introduced

- _episodes/04-data-types-and-format.md
Ensure we import pandas before loading the csv - to be consistent wih the previous lesson.
> Ensure we import pandas before loading the csv

- _episodes/00-before-we-start.md
Added a few lines to the "Before We Start" episode on the topic of the best computational solution. This target is multifaceted and can move beyond just 'what is the best way to code this'.
> expanding-on-best-coding-outcomes

- _episodes/00-before-we-start.md
Indent paragraphs that belong to a list with two spaces.
> 00-before-we-start.md: indent paragraphs that belong to a list

- assets/css/lesson.scss
- setup.md
- Use tabs for OS-specific instructions
- Reword Miniconda-related section
- Merge "Verify Installation" section with "Install Anaconda"
> setup.md: rework, reorganize, improve

- .github/workflows/website.yml
<details>
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
> GH 'Website' action: don't use lesson directory

- _episodes/03-index-slice-subset.md
Error in object name, changed `ref_survey_df` to `ref_surveys_df`
<details>
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, …
> Update 03-index-slice-subset.md, fixed error in object name

- _episodes/07-visualization-ggplot-python.md
Alt-text suggestions for some images in this lesson made by @talishask and me during Core Team Accessibility session. Ready for review.
> adding alt-text to images and illustrations

- _includes/scripts/check_env.py
- environment.yml
- setup.md
Addressing parts of #490
* I've added an environment.yml file to the root directory (wasn't sure where to put it exactly).
* I updated the setup.md to include information on how to use conda to create the environment file referenced above.
* Adjusted the check_env.py script to check for plotnine and not ggplot. Also, fixed the check with newer anaconda installs using capital A, Anaconda path.
> adding environment.yml and instructions

- _episodes/08-putting-it-all-together.md
I'm very confused about that section in 08-putting-it-all-together. These are some simple improvement suggestions (particularly based on the [text "September 11 through 15"](https://github.com/datacarpentry/python-ecology-lesson/blame/3adda6a28161bb6ddacb30f819e8a0c95acc2498/_episodes/08-putting-it-all-together.md#L269)).
Additionally, we could clarify in this PR:
> Align "Pandas and matplotlib" answer code with challenge text

- _episodes/01-short-introduction-to-Python.md
* Fix questions 1st episode (introduction to python programming) (the old questions were a copy from the 0th episode that is an introduction to python and why we should learn it, I changed them to reflect the content of the episode)
* Add time for challenges
> Fix questions introduction episode

- _episodes/02-starting-with-data.md
Issue #496 : Fixed mislabelled cells.
> #496 Fixed mislabelled cells.md

- _episodes/05-merging-data.md
There is no `data_output` directory nor has this been created at this point (lines 126 & 136)  in the lesson. Suggest changing to `data` :)
<details>
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance …
> Update 05-merging-data.md, possible mistake in output directory  name

- _extras/guide.md
Also, clearly distinguish advice on writing out data
> Add solution to Challenge - Counting

- _episodes/05-merging-data.md
- _episodes/09-working-with-sql.md
Hi,
I have made changes in Lesson: Data Analysis and Visualization for Ecologists: Episodes 05 and 09. This is for Carpentries Instructor Checkout. 
Thank you!
Silvina
> I corrected some typos for Carpentries Instructor checkout

- _episodes/01-short-introduction-to-Python.md
Issue #497 : Removed repeated line of code "rev = {'first': 'one', 'second': 'two'}".
> Improved dictionaries - short-introduction-to-Python.md

- _episodes/02-starting-with-data.md
The specific usage of the function `read_csv` didn't match the flow of the other objectives, and the learners at this point will only learn how to import datasets into Python using Pandas.
> cleaner objective

- _episodes/02-starting-with-data.md
> correct surveys.csv table output

- _episodes/03-index-slice-subset.md
<details>
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
> lesson 3 proposal

- _episodes/02-starting-with-data.md
When I was practicing the lesson, I felt it was important to highlight the distinction between attributes & methods. 
Also, when introducing the dataset, making sure that the instructor & learner emphasize that the dataset primarily contains information regarding the species & weight of animals is helpful.
Additionally, one capitalization fix in a subheading.
> improved flow using bold and fixed capitalization

- .github/PULL_REQUEST_TEMPLATE.md
- _includes/check_transition_variables.html
- _includes/lesson_footer.html
- _includes/life_cycle.html
- _includes/navbar.html
- _layouts/base.html
- assets/css/lesson.scss
- bin/boilerplate/_config.yml
Bringing the lesson template up-to-date in preparation for the planned infrastructure transition.
> Update to final version of styles lesson template

- episodes/01-short-introduction-to-Python.md
> Issue 527: do not use word processors

- episodes/02-starting-with-data.md
Fix for issue #486. Changes factors to categories.
> update reference to R data types

- episodes/04-data-types-and-format.md
- instructors/instructor-notes.md
This PR moves the solutions for challenges in episode 5, _Data Types and Formats_, out of the Instructor Notes page and into the episode itself.
This is related to #542
> relocate solutions for episode 04

- episodes/02-starting-with-data.md
- episodes/03-index-slice-subset.md
- episodes/07-visualization-ggplot-python.md
- instructors/instructor-notes.md
Moving a last few pieces of episode-specific guidance inline, to complete the tidy-up of the Instructor Notes page.
> Inline instructor notes

- episodes/00-before-we-start.md
Added some returns and removed stray <br/> so that sandpaper could recognize the headings. Otherwise the lesson would be produced with the formatting hash marks.
> Fix some headings in episode 00 after transition

- episodes/00-before-we-start.md
> remove "easy" from conda description

- learners/setup.md
Fix #575 on my bad advice of adding an extra /
> remove extra /

- learners/setup.md
See https://github.com/datacarpentry/python-ecology-lesson/issues/574#issuecomment-1633312760
> Correctly use relative path for environment.yml

- episodes/03-index-slice-subset.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
closes #579
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
The existing statement would raise
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the …
> Update invalid pandas indexing statement

- learners/reference.md
Python dictionaries are ordered.
> Note Python dictionary is ordered

- learners/jupyter_notebooks.md
Change control to command per the jupyter documentation.
> Close #611
